project_dir:
    '/ccmb/BioinfCore/ActiveProjects/LSA_Denver_rdenver_CS3_cjsifuen_HI-2582/'
email_address:
    'cjsifuen@umich.edu'
analysis_dir_suffix: 
    'analysis_01_25/'
input_dir:
    fastq: '/ccmb/BioinfCore/DNASeqCore/Run_2582/denver/Run_2582/denver/'
    genome_fasta: '/home/cjsifuen/references/mouse/bwa/Mus_musculus.GRCm38.dna.primary_assembly.fa'
    genome_gtf: '/home/cjsifuen/references/mouse/bwa/Mus_musculus.GRCm38.95.gtf'
genome: 
    'GRCm38' 
library_info:
    strandedness: 1 #one of (1) unstranded, (2) forward, (3) reverse
read_info:
    paired_ext: []
thread_info:
    alignment: 20
    fastqc: 6
    index: 20
    trim: 5
    ataqv: 16
    phantompeakqual: 20
    deeptools: 40
    pepr: 20
fastq_screen:
    aligner: 'bowtie2'
    subset: 10000
    multi_species: '/ccmb/BioinfCore/Common/pipelines/Watermelon/references/fastq_screen/multi_species.conf'
    biotype: '/ccmb/BioinfCore/Common/pipelines/Watermelon/references/fastq_screen/mouse.conf'
trim:
    trimq: 20
    minlen: 30
    adaptor: '/sw/med/centos7/bbmap/37.90/resources/adapters.fa'
fastq_info:
    read_length: 50
star_info:
    gene: 'gene_name'
mark_duplicates:
    assumesorted: 'true'
    validationstringency: 'LENIENT'
    createindex: 'true'
filter_bam:
    mapquality: 30
macs2:
    format: 'BEDPE'
    genome_size: 1137453808
    shape: 'broad'
plotFingerprint:
    extendReads: 100
    numberOfSamples: 500000
    binSize: 500
bamCoverage:
    extendReads: 100
    normalizeUsing: 'RPKM'
    binSize: 50
multiBamSummary:
    extendReads: 100
    binSize: 10000
phantompeakqual:
    run: 'Y' #add Y to run
ngsplot:
    genome: 'mm10'
    ensembl: 'Y' #add Y if genome was from ensembl
macs2:
    diff: #add Y if want to call diff 
    metadata: '/ccmb/BioinfCore/ActiveProjects/LSA_Denver_rdenver_CS3_cjsifuen_HI-2582/sample_metadata.txt'
    contrast: '/ccmb/BioinfCore/ActiveProjects/LSA_Denver_rdenver_CS3_cjsifuen_HI-2582/contrasts.txt'
pepr_info:
    peak_type: 'sharp'
    normalization_type: 'inter-group'
    format: 'bam'
    threshold: '0.05'
    window: '200'
    shiftsize: '200'
pepr_groups:
    klf13:
        input: ['Sample_117004', 'Sample_117005', 'Sample_117006', 'Sample_117007']
        chip: ['Sample_118382', 'Sample_118383', 'Sample_118384', 'Sample_118385']
pepr_chipseeker:
    txdb: 'TxDb.Mmusculus.UCSC.mm10.knownGene'
    annodb: 'org.Mm.eg.db'
    
